Test fail

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -398,11 +398,18 @@ jobs:
           
           curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello
           if [ $? -ne 0 ]; then
+            echo "echo "Project generated from archetype ${archetype} failed to start locally."
             cat $logFilePath
             exit 1
           fi
           
           grep -q "I am running!" $logFilePath"
+          if [ $? -ne 0 ]; then
+            echo "Project generated from archetype ${archetype} started locally, but did not contain the expected log output."
+            cat $logFilePath
+            exit 1
+          fi
+          
           if grep -iq "caused by" $logFilePath; then
             echo "Error in log file:"
             cat $logFilePath
