Cache at the end

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -392,6 +392,19 @@ jobs:
       - name: Purge SDK Artifacts from Maven Repository
         run: |
           rm -rf $HOME/.m2/repository/com/sap/cloud/sdk/
+      - name: Start ${{ matrix.task.archetype }}
+        working-directory: ./example-${{ matrix.task.archetype }}/application
+        run: |
+          logFilePath=log.txt
+          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
+          curl --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello || cat log.txt && exit 1
+          
+          grep -q \"I am running!\" $logFilePath"
+          if grep -iq \"caused by\" $logFilePath; then
+            echo \"Error in log file:\"
+            cat $logFilePath
+            exit 1
+          fi
       - name: Save Maven Repository
         uses: actions/cache/save@v3
         if: steps.restore-cache.outputs.cache-hit != 'true'
@@ -399,19 +412,6 @@ jobs:
         with:
           path: ~/.m2/repository
           key: maven-central
-      - name: Start ${{ matrix.task.archetype }}
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: |
-          ${{ matrix.task.startCommand }} > log.txt 2>&1 &
-          curl --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello || cat log.txt && exit 1
-          
-          logFilePath=application/log.txt
-          grep -q \"I am running!\" $logFilePath"
-          if grep -iq \"caused by\" $logFilePath; then
-            echo \"Error in log file:\"
-            cat $logFilePath
-            exit 1
-          fi
           
       
           
