throwaway: disable most of build pipeline

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -13,28 +13,28 @@ env:
   MVN_SKIP_ARGS: "-DskipFormatting -Denforcer.skip -Djacoco.skip -Dmdep.analyze.skip"
 
 jobs:
-  debug-info:
-    runs-on: ubuntu-latest
-    name: Print GitHub Context
-    steps:
-      - name: Print GitHub Context
-        run: echo "${{ toJson(github) }}"
-
-  ### Verify formatting ###
-  # this is done first because it is fast and we don't want to waste time on the other, more expensive steps
-  formatting:
-    runs-on: ubuntu-latest
-    name: Verify Formatting
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: Verify Formatting
-        uses: ./.github/actions/verify-formatting
+#  debug-info:
+#    runs-on: ubuntu-latest
+#    name: Print GitHub Context
+#    steps:
+#      - name: Print GitHub Context
+#        run: echo "${{ toJson(github) }}"
+#
+#  ### Verify formatting ###
+#  # this is done first because it is fast and we don't want to waste time on the other, more expensive steps
+#  formatting:
+#    runs-on: ubuntu-latest
+#    name: Verify Formatting
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Setup Java
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: Verify Formatting
+#        uses: ./.github/actions/verify-formatting
 
   build:
     runs-on: ubuntu-latest
@@ -54,26 +54,26 @@ jobs:
           java-version: 17
       - name: Load Maven Repository
         uses: ./.github/actions/unstash-non-sdk-m2
-      - name: Compile
-        # we need to use install here because otherwise the code checks below don't work
-        # they require the JARs of all modules to work, so those need to be installed
-        run: |
-          python .pipeline/scripts/generate-javadoc-sourcepath-properties.py
-          mvn $MVN_CLI_ARGS install -DskipTests -DskipFormatting -Pdocs
-          python .pipeline/scripts/generate-release-artifacts.py --version ${{ steps.get-version.outputs.VERSION }} --path-prefix release
-          zip -q -r sap-cloud-sdk-java-${{ steps.get-version.outputs.VERSION }}.zip release
-          rm -rf release
-      - name: Create module-inventory
-        run: |
-          python ./scripts/create_module_inventory_file.py --sdk-root-directory ./ --output-file ./module-inventory.json --script-config ./scripts/common/_maven_module/maven_module_reader_configuration.json
-      - name: Local Changes Check
-        uses: ./.github/actions/verify-local-changes
-      - name: Upload release package
-        uses: actions/upload-artifact@v3
-        with:
-          name: cloud-sdk-package
-          path: sap-cloud-sdk-java-${{ steps.get-version.outputs.VERSION }}.zip
-          retention-days: 1
+#      - name: Compile
+#        # we need to use install here because otherwise the code checks below don't work
+#        # they require the JARs of all modules to work, so those need to be installed
+#        run: |
+#          python .pipeline/scripts/generate-javadoc-sourcepath-properties.py
+#          mvn $MVN_CLI_ARGS install -DskipTests -DskipFormatting -Pdocs
+#          python .pipeline/scripts/generate-release-artifacts.py --version ${{ steps.get-version.outputs.VERSION }} --path-prefix release
+#          zip -q -r sap-cloud-sdk-java-${{ steps.get-version.outputs.VERSION }}.zip release
+#          rm -rf release
+#      - name: Create module-inventory
+#        run: |
+#          python ./scripts/create_module_inventory_file.py --sdk-root-directory ./ --output-file ./module-inventory.json --script-config ./scripts/common/_maven_module/maven_module_reader_configuration.json
+#      - name: Local Changes Check
+#        uses: ./.github/actions/verify-local-changes
+#      - name: Upload release package
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: cloud-sdk-package
+#          path: sap-cloud-sdk-java-${{ steps.get-version.outputs.VERSION }}.zip
+#          retention-days: 1
 
       - name: Save Non-SDK Maven Repository
         uses: ./.github/actions/stash-non-sdk-m2
@@ -86,40 +86,40 @@ jobs:
           key: sdk-target-dirs
           force-update: true
 
-  test:
-    needs: build
-    runs-on: ubuntu-latest
-    # Permissions block is optional, useful for dependabot checks
-    permissions:
-      checks: write
-      contents: read
-    name: Test
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup java
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: Load Non-SDK Maven Repository
-        uses: ./.github/actions/unstash-non-sdk-m2
-      - name: Load SDK Maven Repository
-        uses: ./.github/actions/unstash-sdk-m2
-      - name: Load SDK Target Dirs
-        uses: ./.github/actions/unstash
-        with:
-          path: "./**/target/*"
-          key: sdk-target-dirs
-
-      - name: Test
-        run: |
-          mvn $MVN_CLI_ARGS_SINGLE_THREAD org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report
-      - name: Test Report
-        if: success() || failure()
-        uses: scacap/action-surefire-report@v1
-      - name: Coverage Report
-        run: |
-          python .pipeline/scripts/print-coverage.py --jacoco-report-pattern '**/target/site/jacoco/jacoco.csv'
+#  test:
+#    needs: build
+#    runs-on: ubuntu-latest
+#    # Permissions block is optional, useful for dependabot checks
+#    permissions:
+#      checks: write
+#      contents: read
+#    name: Test
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Setup java
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: Load Non-SDK Maven Repository
+#        uses: ./.github/actions/unstash-non-sdk-m2
+#      - name: Load SDK Maven Repository
+#        uses: ./.github/actions/unstash-sdk-m2
+#      - name: Load SDK Target Dirs
+#        uses: ./.github/actions/unstash
+#        with:
+#          path: "./**/target/*"
+#          key: sdk-target-dirs
+#
+#      - name: Test
+#        run: |
+#          mvn $MVN_CLI_ARGS_SINGLE_THREAD org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report
+#      - name: Test Report
+#        if: success() || failure()
+#        uses: scacap/action-surefire-report@v1
+#      - name: Coverage Report
+#        run: |
+#          python .pipeline/scripts/print-coverage.py --jacoco-report-pattern '**/target/site/jacoco/jacoco.csv'
 
 #  checkstyle:
 #    needs: build
@@ -297,33 +297,33 @@ jobs:
 #        with:
 #          category: "/language:java"
 
-  archetypes:
-    runs-on: ubuntu-latest
-    needs: build
-    permissions:
-      checks: write
-      contents: read
-    strategy:
-      matrix:
-        task:
-          - {
-              "archetype": "spring-boot3",
-              "javaVersion": 17,
-              "startCommand": "mvn spring-boot:run -B",
-            }
-    name: Test Archetype ${{ matrix.task.archetype }}
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.task.javaVersion }}
-
-      - name: Verify Archetype
-        uses: ./.github/actions/verify-archetype
-        with:
-          archetype: ${{ matrix.task.archetype }}
+#  archetypes:
+#    runs-on: ubuntu-latest
+#    needs: build
+#    permissions:
+#      checks: write
+#      contents: read
+#    strategy:
+#      matrix:
+#        task:
+#          - {
+#              "archetype": "spring-boot3",
+#              "javaVersion": 17,
+#              "startCommand": "mvn spring-boot:run -B",
+#            }
+#    name: Test Archetype ${{ matrix.task.archetype }}
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Setup Java
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: ${{ matrix.task.javaVersion }}
+#
+#      - name: Verify Archetype
+#        uses: ./.github/actions/verify-archetype
+#        with:
+#          archetype: ${{ matrix.task.archetype }}
 
 #  deploy-snapshot:
 #    name: Deploy Snapshot
