throwaway: comment QA to speed up testing

diff --git a/.github/workflows/continuous-integration.yaml b/.github/workflows/continuous-integration.yaml
--- a/.github/workflows/continuous-integration.yaml
+++ b/.github/workflows/continuous-integration.yaml
@@ -193,265 +193,265 @@ jobs:
           path: ${{ env.SDK_TARGETS_PATH }}
           retention-days: 1
 
-  test:
-    name: "Test"
-    needs: [ context, build ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ needs.context.outputs.commit }}
-      - name: "Setup java"
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: "Restore Dependencies"
-        id: restore-dependencies
-        uses: actions/cache/restore@v3
-        with:
-          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
-          path: ${{ env.M2_ROOT }}
-      - name: "Restore SDK M2"
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.SDK_M2_NAME }}
-          path: ${{ env.M2_ROOT }}
-      - name: "Restore SDK Targets"
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.SDK_TARGETS_NAME }}
-
-      - name: "Run Unit Tests"
-        run: |
-          MVN_ARGS="${{ env.MVN_SINGLE_THREADED_ARGS }} org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report"
-
-          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
-          mvn $MVN_ARGS
-
-      - name: "Test Report"
-        if: github.event.pull_request.head.repo.full_name == 'SAP/cloud-sdk-java'
-        uses: scacap/action-surefire-report@v1
-      - name: Coverage Report
-        run: python .pipeline/scripts/print-coverage.py --jacoco-report-pattern "**/target/site/jacoco/jacoco.csv"
-
-  static-code-analysis:
-    needs: [ context, build ]
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        task:
-          - {
-            "name": "Checkstyle",
-            "mvn_goal": "-P!build-test-modules org.apache.maven.plugins:maven-checkstyle-plugin:checkstyle",
-            "report": ".pipeline/scripts/print-checkstyle.py"
-          }
-          - {
-            "name": "PMD",
-            "mvn_goal": "org.apache.maven.plugins:maven-pmd-plugin:pmd",
-            "report": ".pipeline/scripts/print-pmd.py"
-          }
-          - {
-            "name": "Spotbugs",
-            "mvn_goal": "com.github.spotbugs:spotbugs-maven-plugin:spotbugs",
-            "report": ".pipeline/scripts/print-spotbugs.py"
-          }
-    name: "Run ${{ matrix.task.name }} Analysis"
-    steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ needs.context.outputs.commit }}
-      - name: "Setup java"
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: "Restore Dependencies"
-        id: restore-dependencies
-        uses: actions/cache/restore@v3
-        with:
-          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
-          path: ${{ env.M2_ROOT }}
-      - name: "Restore SDK M2"
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.SDK_M2_NAME }}
-          path: ${{ env.M2_ROOT }}
-      - name: "Restore SDK Targets"
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.SDK_TARGETS_NAME }}
-
-      - name: "Run ${{ matrix.task.name }} Analysis"
-        run: |
-          MVN_ARGS="${{ env.MVN_SINGLE_THREADED_ARGS }} ${{ env.MVN_SKIP_CI_PLUGINS }} ${{ matrix.task.mvn_goal }}"
-
-          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
-          mvn $MVN_ARGS
-
-          python ${{ matrix.task.report }}
-
-  code-ql:
-    name: "Run CodeQL Analysis"
-    needs: [ context ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ needs.context.outputs.commit }}
-      - name: "Setup java"
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: "Restore Dependencies"
-        id: restore-dependencies
-        uses: actions/cache/restore@v3
-        with:
-          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
-          path: ${{ env.DEPENDENCIES_PATH }}
-
-      - name: "Initialize CodeQL"
-        uses: github/codeql-action/init@v2
-        with:
-          languages: "java"
-          queries: security-extended
-
-      - name: "Build SDK"
-        run: |
-          MVN_ARGS="${{ env.MVN_MULTI_THREADED_ARGS }} install -Dmaven.test.skip=true ${{ env.MVN_SKIP_CI_PLUGINS }}"
-
-          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
-          mvn $MVN_ARGS
-
-      - name: "Perform CodeQL Analysis"
-        uses: github/codeql-action/analyze@v2
-        with:
-          category: "/language:java"
-
-  test-archetypes:
-    runs-on: ubuntu-latest
-    needs: [ context, build ]
-    strategy:
-      matrix:
-        task:
-          - {
-            "archetype": "spring-boot3",
-            "javaVersion": 17,
-            "startCommand": "mvn spring-boot:run -B",
-          }
-    name: "Test ${{ matrix.task.archetype }} Archetype"
-    steps:
-      - name: "Setup java"
-        uses: actions/setup-java@v3
-        with:
-          distribution: "temurin"
-          java-version: 17
-      - name: "Restore Dependencies"
-        id: restore-dependencies
-        uses: actions/cache/restore@v3
-        with:
-          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
-          path: ${{ env.DEPENDENCIES_PATH }}
-      - name: "Restore SDK M2"
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.SDK_M2_NAME }}
-          path: ${{ env.M2_ROOT }}
-
-      - name: "Generate ${{ matrix.task.archetype }}"
-        run: >
-          mvn archetype:generate -B
-          -DarchetypeCatalog=local
-          -DarchetypeGroupId=com.sap.cloud.sdk.archetypes
-          -DarchetypeArtifactId=${{ matrix.task.archetype }}
-          -DgroupId=com.sap.test
-          -DartifactId=example-${{ matrix.task.archetype }}
-          -Dversion=1.0-SNAPSHOT
-          -Dpackage=com.sap.test
-          -Dhttp.keepAlive=false
-
-      - name: "Verify ${{ matrix.task.archetype }}"
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: >
-          mvn clean verify -B
-          -Dhttp.keepAlive=false
-          -Dmaven.test.skip=true
-
-      - name: "Test ${{ matrix.task.name }}"
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: mvn test -B -Dsurefire.logLevel='error'
-
-      - name: "Spotbugs ${{ matrix.task.archetype }}"
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: >
-          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
-          -Dhttp.keepAlive=false
-          -Dmaven.wagon.http.pool=false
-
-      - name: "Start ${{ matrix.task.archetype }}"
-        working-directory: ./example-${{ matrix.task.archetype }}/application
-        run: |
-          logFilePath=log.txt
-          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
-
-          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
-            echo "Project generated from archetype '${{ matrix.task.archetype }}' failed to start locally."
-            cat $logFilePath
-            exit 1
-          fi
-
-          if ! grep -q "I am running!" $logFilePath; then
-            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but did not contain the expected log output."
-            cat $logFilePath
-            exit 1
-          fi
-
-          if grep -iq "caused by" $logFilePath; then
-            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but an unexpected error occurred."
-            cat $logFilePath
-            exit 1
-          fi
-
-      - name: "Verify .gitignore ${{ matrix.task.archetype }}"
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: |
-          if [[ ! -f .gitignore ]]; then
-              ls -lah
-              echo "Project generated from archetype '${{ matrix.task.archetype }}' does not contain a .gitignore file."
-              exit 1
-          fi
-
-  blackduck:
-    name: "Run BlackDuck Scan"
-    if: ${{ github.event.inputs.run-blackduck-scan == 'true' }}
-    needs: [ context ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ needs.context.outputs.commit }}
-
-      - name: "Scan With Black Duck"
-        uses: ./.github/actions/scan-with-blackduck
-
-  security-rating:
-    name: "Run Security Rating"
-    if: ${{ github.event.inputs.run-security-rating == 'true' }}
-    needs: [ context ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Checkout repository"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ needs.context.outputs.commit }}
-
-      - name: "Run FOSStars Rating"
-        uses: SAP/fosstars-rating-core-action@v1.14.0
-        with:
-          report-branch: fosstars-report
-          token: ${{ github.token }}
+#  test:
+#    name: "Test"
+#    needs: [ context, build ]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: "Checkout repository"
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ needs.context.outputs.commit }}
+#      - name: "Setup java"
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: "Restore Dependencies"
+#        id: restore-dependencies
+#        uses: actions/cache/restore@v3
+#        with:
+#          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
+#          path: ${{ env.M2_ROOT }}
+#      - name: "Restore SDK M2"
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{ env.SDK_M2_NAME }}
+#          path: ${{ env.M2_ROOT }}
+#      - name: "Restore SDK Targets"
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{ env.SDK_TARGETS_NAME }}
+#
+#      - name: "Run Unit Tests"
+#        run: |
+#          MVN_ARGS="${{ env.MVN_SINGLE_THREADED_ARGS }} org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report"
+#
+#          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
+#          mvn $MVN_ARGS
+#
+#      - name: "Test Report"
+#        if: github.event.pull_request.head.repo.full_name == 'SAP/cloud-sdk-java'
+#        uses: scacap/action-surefire-report@v1
+#      - name: Coverage Report
+#        run: python .pipeline/scripts/print-coverage.py --jacoco-report-pattern "**/target/site/jacoco/jacoco.csv"
+#
+#  static-code-analysis:
+#    needs: [ context, build ]
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        task:
+#          - {
+#            "name": "Checkstyle",
+#            "mvn_goal": "-P!build-test-modules org.apache.maven.plugins:maven-checkstyle-plugin:checkstyle",
+#            "report": ".pipeline/scripts/print-checkstyle.py"
+#          }
+#          - {
+#            "name": "PMD",
+#            "mvn_goal": "org.apache.maven.plugins:maven-pmd-plugin:pmd",
+#            "report": ".pipeline/scripts/print-pmd.py"
+#          }
+#          - {
+#            "name": "Spotbugs",
+#            "mvn_goal": "com.github.spotbugs:spotbugs-maven-plugin:spotbugs",
+#            "report": ".pipeline/scripts/print-spotbugs.py"
+#          }
+#    name: "Run ${{ matrix.task.name }} Analysis"
+#    steps:
+#      - name: "Checkout repository"
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ needs.context.outputs.commit }}
+#      - name: "Setup java"
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: "Restore Dependencies"
+#        id: restore-dependencies
+#        uses: actions/cache/restore@v3
+#        with:
+#          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
+#          path: ${{ env.M2_ROOT }}
+#      - name: "Restore SDK M2"
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{ env.SDK_M2_NAME }}
+#          path: ${{ env.M2_ROOT }}
+#      - name: "Restore SDK Targets"
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{ env.SDK_TARGETS_NAME }}
+#
+#      - name: "Run ${{ matrix.task.name }} Analysis"
+#        run: |
+#          MVN_ARGS="${{ env.MVN_SINGLE_THREADED_ARGS }} ${{ env.MVN_SKIP_CI_PLUGINS }} ${{ matrix.task.mvn_goal }}"
+#
+#          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
+#          mvn $MVN_ARGS
+#
+#          python ${{ matrix.task.report }}
+#
+#  code-ql:
+#    name: "Run CodeQL Analysis"
+#    needs: [ context ]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: "Checkout repository"
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ needs.context.outputs.commit }}
+#      - name: "Setup java"
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: "Restore Dependencies"
+#        id: restore-dependencies
+#        uses: actions/cache/restore@v3
+#        with:
+#          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
+#          path: ${{ env.DEPENDENCIES_PATH }}
+#
+#      - name: "Initialize CodeQL"
+#        uses: github/codeql-action/init@v2
+#        with:
+#          languages: "java"
+#          queries: security-extended
+#
+#      - name: "Build SDK"
+#        run: |
+#          MVN_ARGS="${{ env.MVN_MULTI_THREADED_ARGS }} install -Dmaven.test.skip=true ${{ env.MVN_SKIP_CI_PLUGINS }}"
+#
+#          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
+#          mvn $MVN_ARGS
+#
+#      - name: "Perform CodeQL Analysis"
+#        uses: github/codeql-action/analyze@v2
+#        with:
+#          category: "/language:java"
+#
+#  test-archetypes:
+#    runs-on: ubuntu-latest
+#    needs: [ context, build ]
+#    strategy:
+#      matrix:
+#        task:
+#          - {
+#            "archetype": "spring-boot3",
+#            "javaVersion": 17,
+#            "startCommand": "mvn spring-boot:run -B",
+#          }
+#    name: "Test ${{ matrix.task.archetype }} Archetype"
+#    steps:
+#      - name: "Setup java"
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: "temurin"
+#          java-version: 17
+#      - name: "Restore Dependencies"
+#        id: restore-dependencies
+#        uses: actions/cache/restore@v3
+#        with:
+#          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
+#          path: ${{ env.DEPENDENCIES_PATH }}
+#      - name: "Restore SDK M2"
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{ env.SDK_M2_NAME }}
+#          path: ${{ env.M2_ROOT }}
+#
+#      - name: "Generate ${{ matrix.task.archetype }}"
+#        run: >
+#          mvn archetype:generate -B
+#          -DarchetypeCatalog=local
+#          -DarchetypeGroupId=com.sap.cloud.sdk.archetypes
+#          -DarchetypeArtifactId=${{ matrix.task.archetype }}
+#          -DgroupId=com.sap.test
+#          -DartifactId=example-${{ matrix.task.archetype }}
+#          -Dversion=1.0-SNAPSHOT
+#          -Dpackage=com.sap.test
+#          -Dhttp.keepAlive=false
+#
+#      - name: "Verify ${{ matrix.task.archetype }}"
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: >
+#          mvn clean verify -B
+#          -Dhttp.keepAlive=false
+#          -Dmaven.test.skip=true
+#
+#      - name: "Test ${{ matrix.task.name }}"
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: mvn test -B -Dsurefire.logLevel='error'
+#
+#      - name: "Spotbugs ${{ matrix.task.archetype }}"
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: >
+#          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
+#          -Dhttp.keepAlive=false
+#          -Dmaven.wagon.http.pool=false
+#
+#      - name: "Start ${{ matrix.task.archetype }}"
+#        working-directory: ./example-${{ matrix.task.archetype }}/application
+#        run: |
+#          logFilePath=log.txt
+#          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
+#
+#          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
+#            echo "Project generated from archetype '${{ matrix.task.archetype }}' failed to start locally."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#          if ! grep -q "I am running!" $logFilePath; then
+#            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but did not contain the expected log output."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#          if grep -iq "caused by" $logFilePath; then
+#            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but an unexpected error occurred."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#      - name: "Verify .gitignore ${{ matrix.task.archetype }}"
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: |
+#          if [[ ! -f .gitignore ]]; then
+#              ls -lah
+#              echo "Project generated from archetype '${{ matrix.task.archetype }}' does not contain a .gitignore file."
+#              exit 1
+#          fi
+#
+#  blackduck:
+#    name: "Run BlackDuck Scan"
+#    if: ${{ github.event.inputs.run-blackduck-scan == 'true' }}
+#    needs: [ context ]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: "Checkout repository"
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ needs.context.outputs.commit }}
+#
+#      - name: "Scan With Black Duck"
+#        uses: ./.github/actions/scan-with-blackduck
+#
+#  security-rating:
+#    name: "Run Security Rating"
+#    if: ${{ github.event.inputs.run-security-rating == 'true' }}
+#    needs: [ context ]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: "Checkout repository"
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ needs.context.outputs.commit }}
+#
+#      - name: "Run FOSStars Rating"
+#        uses: SAP/fosstars-rating-core-action@v1.14.0
+#        with:
+#          report-branch: fosstars-report
+#          token: ${{ github.token }}
