clean-up

diff --git a/.github/workflows/continuous-integration.yaml b/.github/workflows/continuous-integration.yaml
--- a/.github/workflows/continuous-integration.yaml
+++ b/.github/workflows/continuous-integration.yaml
@@ -9,7 +9,6 @@ on:
     inputs:
       commit:
         # this commit is what is actually going to be checked out
-        # JONAS: Do I need all of these?
         description: "Commit SHA of the code to be built"
         required: true
       build-release-artifacts:
@@ -35,14 +34,10 @@ on:
 
 env:
   M2_ROOT: ~/.m2/repository
-  RELEASE_ARTIFACT_NAME: "release-artifacts"
   SDK_M2_NAME: "sdk-m2" # used for the installed SDK modules within the runner's maven repository
   SDK_M2_PATH: |
     ~/.m2/repository/com/sap/cloud/sdk/**
     ~/.m2/repository/archetype-catalog.xml
-  SDK_TARGETS_NAME: "sdk-targets" # used for the SDK's target directories
-  SDK_TARGETS_PATH: |
-    ./
 
   # keep the following two variables in sync with our 'cache-maven-dependencies.yaml' workflow
   MAVEN_CACHE_KEY: maven-dependencies
@@ -181,18 +176,13 @@ jobs:
           path: ${{ env.M2_ROOT }}
 
       - name: "Run Unit Tests"
-#        JONAS: remove "exit 0"
         run: |
-          exit 0 
           MVN_ARGS="${{ env.MVN_SINGLE_THREADED_ARGS }} org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report --fail-at-end"
           echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
           mvn $MVN_ARGS
 
       - name: "Coverage Report"
-#        JONAS: remove "exit 0"
-        run: |
-          exit 0
-          python .pipeline/scripts/print-coverage.py --jacoco-report-pattern "**/target/site/jacoco/jacoco.csv"
+        run: python .pipeline/scripts/print-coverage.py --jacoco-report-pattern "**/target/site/jacoco/jacoco.csv"
 
   static-code-analysis:
     needs: [ context, build ]
@@ -256,6 +246,116 @@ jobs:
         with:
           distribution: "sapmachine"
           java-version: 17
+
+      - name: "Initialize CodeQL"
+        uses: github/codeql-action/init@v3
+        with:
+          languages: "java"
+          queries: security-extended
+
+      - name: "Build SDK"
+        run: |
+          MVN_ARGS="${{ env.MVN_MULTI_THREADED_ARGS }} install -Dmaven.test.skip=true ${{ env.MVN_SKIP_CI_PLUGINS }}"
+          echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
+          mvn $MVN_ARGS
+
+      - name: "Perform CodeQL Analysis"
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:java"
+
+  test-archetypes:
+    runs-on: ubuntu-latest
+    needs: [ context, build ]
+    strategy:
+      matrix:
+        task:
+          - {
+            "archetype": "spring-boot3",
+            "javaVersion": 17,
+            "startCommand": "mvn spring-boot:run -B",
+          }
+    name: "Test ${{ matrix.task.archetype }} Archetype"
+    steps:
+      - name: "Setup java"
+        uses: actions/setup-java@v4
+        with:
+          distribution: "sapmachine"
+          java-version: 17
+
+      - name: "Restore Dependencies"
+        id: restore-dependencies
+        uses: actions/cache/restore@v4
+        with:
+          key: ${{ env.MAVEN_CACHE_KEY }}
+          path: ${{ env.MAVEN_CACHE_DIR }}
+
+      - name: "Restore SDK M2"
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.SDK_M2_NAME }}
+          path: ${{ env.M2_ROOT }}
+
+      - name: "Generate ${{ matrix.task.archetype }}"
+        run: >
+          mvn archetype:generate -B
+          -DarchetypeCatalog=local
+          -DarchetypeGroupId=com.sap.cloud.sdk.archetypes
+          -DarchetypeArtifactId=${{ matrix.task.archetype }}
+          -DgroupId=com.sap.test
+          -DartifactId=example-${{ matrix.task.archetype }}
+          -Dversion=1.0-SNAPSHOT
+          -Dpackage=com.sap.test
+          -Dhttp.keepAlive=false
+
+      - name: "Verify ${{ matrix.task.archetype }}"
+        working-directory: ./example-${{ matrix.task.archetype }}
+        run: >
+          mvn clean verify -B
+          -Dhttp.keepAlive=false
+          -Dmaven.test.skip=true
+
+      - name: "Test ${{ matrix.task.name }}"
+        working-directory: ./example-${{ matrix.task.archetype }}
+        run: mvn test -B -Dsurefire.logLevel='error'
+
+      - name: "Spotbugs ${{ matrix.task.archetype }}"
+        working-directory: ./example-${{ matrix.task.archetype }}
+        run: >
+          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
+          -Dhttp.keepAlive=false
+          -Dmaven.wagon.http.pool=false
+
+      - name: "Start ${{ matrix.task.archetype }}"
+        working-directory: ./example-${{ matrix.task.archetype }}/application
+        run: |
+          logFilePath=log.txt
+          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
+
+          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
+            echo "Project generated from archetype '${{ matrix.task.archetype }}' failed to start locally."
+            cat $logFilePath
+            exit 1
+          fi
+          if ! grep -q "I am running!" $logFilePath; then
+            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but did not contain the expected log output."
+            cat $logFilePath
+            exit 1
+          fi
+          if grep -iq "caused by" $logFilePath; then
+            echo "Project generated from archetype '${{ matrix.task.archetype }}' started locally, but an unexpected error occurred."
+            cat $logFilePath
+            exit 1
+          fi
+
+      - name: "Verify .gitignore ${{ matrix.task.archetype }}"
+        working-directory: ./example-${{ matrix.task.archetype }}
+        run: |
+          if [[ ! -f .gitignore ]]; then
+              ls -lah
+              echo "Project generated from archetype '${{ matrix.task.archetype }}' does not contain a .gitignore file."
+              exit 1
+          fi
 
   blackduck:
     name: "Run BlackDuck Scan"
