fix: make sure release PRs are actually okay

diff --git a/.github/workflows/perform-release.yml b/.github/workflows/perform-release.yml
--- a/.github/workflows/perform-release.yml
+++ b/.github/workflows/perform-release.yml
@@ -14,7 +14,8 @@ on:
 env:
   MVN_CLI_ARGS: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
 
-  DOCS_REPO: SAP/cloud-sdk
+  # TODO: use production repo
+  DOCS_REPO: Johannes-Schneider/cloud-sdk
 
 jobs:
   prerequisites:
@@ -57,43 +58,109 @@ jobs:
 
       - name: "Check Whether Code PR Can Be Merged"
         run: |
-          PR=$(gh pr view "${{ steps.determine-branch-names.outputs.CODE_BRANCH_NAME }}" --repo "${{ github.repository }}" --json number,mergeable)
+          PR=$(gh pr view "${{ steps.determine-branch-names.outputs.CODE_BRANCH_NAME }}" --repo "${{ github.repository }}" --json number,reviewDecision,mergeable,statusCheckRollup)
           NUMBER=$(echo "$PR" | jq -r '.number')
+          DECISION=$(echo "$PR" | jq -r '.reviewDecision')
           MERGEABLE=$(echo "$PR" | jq -r '.mergeable')
-          if [[ "$MERGEABLE" == "MERGEABLE" ]]; then
-            echo "[DEBUG] Code PR (#$NUMBER) can be merged."
-          else
-            echo "Code PR (#$NUMBER) cannot be merged."
+          
+          if [[ "$MERGEABLE" != "MERGEABLE" ]]; then
+            echo "Code PR (#$NUMBER) is not mergeable."
             exit 1
           fi
+          
+          if [[ "$DECISION" != "APPROVED" ]]; then
+            echo "Code PR (#$NUMBER) is not approved."
+            exit 1
+          fi
+          
+          STATUS_CHECKS=$(echo "$PR" | jq -r '.statusCheckRollup')
+          FAILED_CHECK_RUNS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "CheckRun" and .conclusion != "SUCCESS" and .conclusion != "NEUTRAL")')
+          if [[ -n "$FAILED_CHECK_RUNS" ]]; then
+            echo "Code PR (#$NUMBER) has failed check runs:"
+            echo "$FAILED_CHECK_RUNS"
+            exit 1
+          fi
+          
+          FAILED_STATUS_CONTEXTS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "StatusContext" and .state != "SUCCESS")')
+          if [[ -n "$FAILED_STATUS_CONTEXTS" ]]; then
+              echo "Code PR (#$NUMBER) has failed status contexts:"
+              echo "$FAILED_STATUS_CONTEXTS"
+              exit 1
+          fi
+          
+          echo "[DEBUG] Code PR (#$NUMBER) can be merged."
         env:
           GH_TOKEN: ${{ github.token }}
 
       - name: "Check Whether Docs PR Can Be Merged"
         run: |
-          PR=$(gh pr view "${{ steps.determine-branch-names.outputs.DOCS_BRANCH_NAME }}" --repo ${{ env.DOCS_REPO }} --json number,mergeable)
-          NUMBER=$(echo "$PR" | jq -r '.number')
-          MERGEABLE=$(echo "$PR" | jq -r '.mergeable')
-          if [[ "$MERGEABLE" == "MERGEABLE" ]]; then
+            PR=$(gh pr view "${{ steps.determine-branch-names.outputs.DOCS_BRANCH_NAME }}" --repo ${{ env.DOCS_REPO }} --json number,reviewDecision,mergeable,statusCheckRollup)
+            NUMBER=$(echo "$PR" | jq -r '.number')
+            DECISION=$(echo "$PR" | jq -r '.reviewDecision')
+            MERGEABLE=$(echo "$PR" | jq -r '.mergeable')
+            
+            if [[ "$MERGEABLE" != "MERGEABLE" ]]; then
+                echo "Docs PR (#$NUMBER) is not mergeable."
+                exit 1
+            fi
+            
+            if [[ "$DECISION" != "APPROVED" ]]; then
+                echo "Docs PR (#$NUMBER) is not approved."
+                exit 1
+            fi
+            
+            STATUS_CHECKS=$(echo "$PR" | jq -r '.statusCheckRollup')
+            FAILED_CHECK_RUNS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "CheckRun" and .conclusion != "SUCCESS" and .conclusion != "NEUTRAL")')
+            if [[ -n "$FAILED_CHECK_RUNS" ]]; then
+                echo "Docs PR (#$NUMBER) has failed check runs:"
+                echo "$FAILED_CHECK_RUNS"
+                exit 1
+            fi
+            
+            FAILED_STATUS_CONTEXTS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "StatusContext" and .state != "SUCCESS")')
+            if [[ -n "$FAILED_STATUS_CONTEXTS" ]]; then
+                echo "Docs PR (#$NUMBER) has failed status contexts:"
+                echo "$FAILED_STATUS_CONTEXTS"
+                exit 1
+            fi
+            
             echo "[DEBUG] Docs PR (#$NUMBER) can be merged."
-          else
-            echo "Docs PR (#$NUMBER) cannot be merged."
-            exit 1
-          fi
         env:
           GH_TOKEN: ${{ secrets.BOT_SDK_JS_FOR_DOCS_REPO_PR }}
 
       - name: "Check Whether Release Notes PR Can Be Merged"
         run: |
-          PR=$(gh pr view "${{ steps.determine-branch-names.outputs.RELEASE_NOTES_BRANCH_NAME }}" --repo ${{ env.DOCS_REPO }} --json number,mergeable)
-          NUMBER=$(echo "$PR" | jq -r '.number')
-          MERGEABLE=$(echo "$PR" | jq -r '.mergeable')
-          if [[ "$MERGEABLE" == "MERGEABLE" ]]; then
+            PR=$(gh pr view "${{ steps.determine-branch-names.outputs.RELEASE_NOTES_BRANCH_NAME }}" --repo ${{ env.DOCS_REPO }} --json number,reviewDecision,mergeable,statusCheckRollup)
+            NUMBER=$(echo "$PR" | jq -r '.number')
+            DECISION=$(echo "$PR" | jq -r '.reviewDecision')
+            MERGEABLE=$(echo "$PR" | jq -r '.mergeable')
+            
+            if [[ "$MERGEABLE" != "MERGEABLE" ]]; then
+                echo "Release Notes PR (#$NUMBER) is not mergeable."
+                exit 1
+            fi
+            
+            if [[ "$DECISION" != "APPROVED" ]]; then
+                echo "Release Notes PR (#$NUMBER) is not approved."
+                exit 1
+            fi
+            
+            STATUS_CHECKS=$(echo "$PR" | jq -r '.statusCheckRollup')
+            FAILED_CHECK_RUNS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "CheckRun" and .conclusion != "SUCCESS" and .conclusion != "NEUTRAL")')
+            if [[ -n "$FAILED_CHECK_RUNS" ]]; then
+                echo "Release Notes PR (#$NUMBER) has failed check runs:"
+                echo "$FAILED_CHECK_RUNS"
+                exit 1
+            fi
+            
+            FAILED_STATUS_CONTEXTS=$(echo $STATUS_CHECKS | jq -r '.[] | select(.__typename == "StatusContext" and .state != "SUCCESS")')
+            if [[ -n "$FAILED_STATUS_CONTEXTS" ]]; then
+                echo "Release Notes PR (#$NUMBER) has failed status contexts:"
+                echo "$FAILED_STATUS_CONTEXTS"
+                exit 1
+            fi
+            
             echo "[DEBUG] Release Notes PR (#$NUMBER) can be merged."
-          else
-            echo "Release Notes PR (#$NUMBER) cannot be merged."
-            exit 1
-          fi
         env:
           GH_TOKEN: ${{ secrets.BOT_SDK_JS_FOR_DOCS_REPO_PR }}
 
