Disable archetypes tests, cleanup

diff --git a/.github/workflows/prepare_release.yml b/.github/workflows/prepare_release.yml
--- a/.github/workflows/prepare_release.yml
+++ b/.github/workflows/prepare_release.yml
@@ -14,6 +14,7 @@ env:
 jobs:
   prepare-release:
     runs-on: ubuntu-latest
+    name: Prepare
     permissions:
       contents: write
       pull-requests: write
@@ -80,7 +81,7 @@ jobs:
     permissions:
       checks: write
       contents: read
-    name: Install
+    name: Test/Install/Package
     outputs:
       version: ${{ steps.get-version.outputs.VERSION }}
     steps:
@@ -96,9 +97,10 @@ jobs:
         with:
           distribution: "temurin"
           java-version: 17
-      - name: Install
+      - name: Test/Install/Package
         run: |
-          mvn $MVN_CLI_ARGS install jacoco:report
+          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.release_version }}
+          zip -q -r sap-cloud-sdk-java-${{ needs.prepare-release.outputs.release_version }}.zip rel-${{ needs.prepare-release.outputs.release_version }}
       - name: Local Changes Check
         run: |
           CHANGED_FILES="$(git --no-pager diff --name-only)"
@@ -140,10 +142,6 @@ jobs:
         run: |
           mvn $MVN_CLI_ARGS com.github.spotbugs:spotbugs-maven-plugin:spotbugs
           python .pipeline/scripts/print-spotbugs.py
-      - name: Create release package
-        run: |
-          mvn -q $MVN_CLI_ARGS package org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.release_version }}
-          zip -q -r sap-cloud-sdk-java-${{ needs.prepare-release.outputs.release_version }}.zip rel-${{ needs.prepare-release.outputs.release_version }}
       - name: Upload release package
         uses: actions/upload-artifact@v3
         with:
@@ -212,66 +210,70 @@ jobs:
           -Dpackage=com.sap.test
           -Dhttp.keepAlive=false
 
-      - name: Verify ${{ matrix.task.archetype }}
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: >
-          mvn clean verify -B
-          -Dhttp.keepAlive=false
-          -Dmaven.test.skip=true
-      - name: Test ${{ matrix.task.name }}
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: mvn test -B -Dsurefire.logLevel='error'
-      - name: Spotbugs ${{ matrix.task.archetype }}
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: >
-          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
-          -pl !integration-tests
-          -Dhttp.keepAlive=false
-          -Dmaven.wagon.http.pool=false
-
-      - name: Start ${{ matrix.task.archetype }}
-        working-directory: ./example-${{ matrix.task.archetype }}/application
+#      - name: Verify ${{ matrix.task.archetype }}
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: >
+#          mvn clean verify -B
+#          -Dhttp.keepAlive=false
+#          -Dmaven.test.skip=true
+#      - name: Test ${{ matrix.task.name }}
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: mvn test -B -Dsurefire.logLevel='error'
+#      - name: Spotbugs ${{ matrix.task.archetype }}
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: >
+#          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
+#          -pl !integration-tests
+#          -Dhttp.keepAlive=false
+#          -Dmaven.wagon.http.pool=false
+#
+#      - name: Start ${{ matrix.task.archetype }}
+#        working-directory: ./example-${{ matrix.task.archetype }}/application
+#        run: |
+#          logFilePath=log.txt
+#          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
+#
+#          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
+#            echo "Project generated from archetype ${{ matrix.task.archetype }} failed to start locally."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#          if ! grep -q "I am running!" $logFilePath; then
+#            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but did not contain the expected log output."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#          if grep -iq "caused by" $logFilePath; then
+#            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but an unexpected error occurred."
+#            cat $logFilePath
+#            exit 1
+#          fi
+#
+#      - name: Verify .gitignore ${{ matrix.task.archetype }}
+#        working-directory: ./example-${{ matrix.task.archetype }}
+#        run: |
+#          if [ ! -f .gitignore ]; then
+#              ls -lah
+#              echo "Project generated from archetype does not contain a .gitignore file."
+#              exit 1
+#          fi
+#
+#      - name: Purge SDK Artifacts from Maven Repository
+#        run: |
+#          rm -rf $HOME/.m2/repository/com/sap/cloud/sdk/
+#      - name: Save Maven Repository
+#        uses: actions/cache/save@v3
+#        if: steps.restore-cache.outputs.cache-hit != 'true'
+#        id: save-cache
+#        with:
+#          path: ~/.m2/repository
+#          key: maven-central
+      - name: Fill summary with TODO
         run: |
-          logFilePath=log.txt
-          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
-
-          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
-            echo "Project generated from archetype ${{ matrix.task.archetype }} failed to start locally."
-            cat $logFilePath
-            exit 1
-          fi
-
-          if ! grep -q "I am running!" $logFilePath; then
-            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but did not contain the expected log output."
-            cat $logFilePath
-            exit 1
-          fi
-
-          if grep -iq "caused by" $logFilePath; then
-            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but an unexpected error occurred."
-            cat $logFilePath
-            exit 1
-          fi
-
-      - name: Verify .gitignore ${{ matrix.task.archetype }}
-        working-directory: ./example-${{ matrix.task.archetype }}
-        run: |
-          if [ ! -f .gitignore ]; then
-              ls -lah
-              echo "Project generated from archetype does not contain a .gitignore file."
-              exit 1
-          fi
-
-      - name: Purge SDK Artifacts from Maven Repository
-        run: |
-          rm -rf $HOME/.m2/repository/com/sap/cloud/sdk/
-      - name: Save Maven Repository
-        uses: actions/cache/save@v3
-        if: steps.restore-cache.outputs.cache-hit != 'true'
-        id: save-cache
-        with:
-          path: ~/.m2/repository
-          key: maven-central
+          echo "# TODO" >> $GITHUB_STEP_SUMMARY
+          echo "Enable archetypes tests once all modules are migrated to github.com!" >> $GITHUB_STEP_SUMMARY
 
   codeql:
     name: Analyze with CodeQL
@@ -316,6 +318,7 @@ jobs:
   create-release:
     runs-on: ubuntu-latest
     needs: [archetypes, codeql, prepare-release]
+    name: Create Draft Release
     permissions:
       contents: write
       pull-requests: write
