Add Blackduck and Fosstars

diff --git a/.github/workflows/prepare_release.yml b/.github/workflows/prepare_release.yml
--- a/.github/workflows/prepare_release.yml
+++ b/.github/workflows/prepare_release.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       release_version:
-        description: 'Release version, leave empty for default value based on current snapshot'
+        description: "Release version, leave empty for default value based on current snapshot"
         required: false
 
 env:
@@ -26,8 +26,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-        with:
-          ref: 'main'
+        # with:
+        #   ref: 'main'
 
       - name: Setup java
         uses: actions/setup-java@v3
@@ -43,9 +43,9 @@ jobs:
         env:
           INPUT_VERSION: ${{ github.event.inputs.release_version }}
 
-      - run: 'echo Release Version: ${{ steps.get-release-versions.outputs.RELEASE_VERSION }}'
-      - run: 'echo Current Snapshot: ${{ steps.get-release-versions.outputs.CURRENT_SNAPSHOT }}'
-      - run: 'echo New Snapshot: ${{ steps.get-release-versions.outputs.NEW_SNAPSHOT }}'
+      - run: "echo Release Version: ${{ steps.get-release-versions.outputs.RELEASE_VERSION }}"
+      - run: "echo Current Snapshot: ${{ steps.get-release-versions.outputs.CURRENT_SNAPSHOT }}"
+      - run: "echo New Snapshot: ${{ steps.get-release-versions.outputs.NEW_SNAPSHOT }}"
 
       - name: Prepare git
         run: |
@@ -69,7 +69,6 @@ jobs:
           echo "RELEASE_COMMIT_ID=$RELEASE_COMMIT_ID" >> $GITHUB_OUTPUT
 
           git push origin $BRANCH_NAME:$BRANCH_NAME
-
 
   build:
     needs: prepare-release
@@ -156,15 +155,15 @@ jobs:
       matrix:
         task:
           - {
-            "archetype": "scp-cf-spring",
-            "javaVersion": 8,
-            "startCommand": "mvn spring-boot:run -B",
-          }
+              "archetype": "scp-cf-spring",
+              "javaVersion": 8,
+              "startCommand": "mvn spring-boot:run -B",
+            }
           - {
-            "archetype": "scp-cf-spring-jakarta",
-            "javaVersion": 17,
-            "startCommand": "mvn spring-boot:run -B",
-          }
+              "archetype": "scp-cf-spring-jakarta",
+              "javaVersion": 17,
+              "startCommand": "mvn spring-boot:run -B",
+            }
     name: ${{ matrix.task.archetype }}
     steps:
       - name: Setup Java
@@ -207,66 +206,66 @@ jobs:
           -Dpackage=com.sap.test
           -Dhttp.keepAlive=false
 
-#      - name: Verify ${{ matrix.task.archetype }}
-#        working-directory: ./example-${{ matrix.task.archetype }}
-#        run: >
-#          mvn clean verify -B
-#          -Dhttp.keepAlive=false
-#          -Dmaven.test.skip=true
-#      - name: Test ${{ matrix.task.name }}
-#        working-directory: ./example-${{ matrix.task.archetype }}
-#        run: mvn test -B -Dsurefire.logLevel='error'
-#      - name: Spotbugs ${{ matrix.task.archetype }}
-#        working-directory: ./example-${{ matrix.task.archetype }}
-#        run: >
-#          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
-#          -pl !integration-tests
-#          -Dhttp.keepAlive=false
-#          -Dmaven.wagon.http.pool=false
-#
-#      - name: Start ${{ matrix.task.archetype }}
-#        working-directory: ./example-${{ matrix.task.archetype }}/application
-#        run: |
-#          logFilePath=log.txt
-#          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
-#
-#          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
-#            echo "Project generated from archetype ${{ matrix.task.archetype }} failed to start locally."
-#            cat $logFilePath
-#            exit 1
-#          fi
-#
-#          if ! grep -q "I am running!" $logFilePath; then
-#            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but did not contain the expected log output."
-#            cat $logFilePath
-#            exit 1
-#          fi
-#
-#          if grep -iq "caused by" $logFilePath; then
-#            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but an unexpected error occurred."
-#            cat $logFilePath
-#            exit 1
-#          fi
-#
-#      - name: Verify .gitignore ${{ matrix.task.archetype }}
-#        working-directory: ./example-${{ matrix.task.archetype }}
-#        run: |
-#          if [ ! -f .gitignore ]; then
-#              ls -lah
-#              echo "Project generated from archetype does not contain a .gitignore file."
-#              exit 1
-#          fi
-#
-#      - name: Purge SDK Artifacts from Maven Repository
-#        run: |
-#          rm -rf $HOME/.m2/repository/com/sap/cloud/sdk/
-#      - name: Save Maven Repository
-#        uses: actions/cache/save@v3
-#        if: steps.restore-cache.outputs.cache-hit != 'true'
-#        id: save-cache
-#        with:
-#          path: ~/.m2/repository
-#          key: maven-central
+      #      - name: Verify ${{ matrix.task.archetype }}
+      #        working-directory: ./example-${{ matrix.task.archetype }}
+      #        run: >
+      #          mvn clean verify -B
+      #          -Dhttp.keepAlive=false
+      #          -Dmaven.test.skip=true
+      #      - name: Test ${{ matrix.task.name }}
+      #        working-directory: ./example-${{ matrix.task.archetype }}
+      #        run: mvn test -B -Dsurefire.logLevel='error'
+      #      - name: Spotbugs ${{ matrix.task.archetype }}
+      #        working-directory: ./example-${{ matrix.task.archetype }}
+      #        run: >
+      #          mvn com.github.spotbugs:spotbugs-maven-plugin:check -B
+      #          -pl !integration-tests
+      #          -Dhttp.keepAlive=false
+      #          -Dmaven.wagon.http.pool=false
+      #
+      #      - name: Start ${{ matrix.task.archetype }}
+      #        working-directory: ./example-${{ matrix.task.archetype }}/application
+      #        run: |
+      #          logFilePath=log.txt
+      #          ${{ matrix.task.startCommand }} > $logFilePath 2>&1 &
+      #
+      #          if ! curl -s --retry 60 --retry-delay 3 --retry-all-errors http://127.0.0.1:8080/hello ; then
+      #            echo "Project generated from archetype ${{ matrix.task.archetype }} failed to start locally."
+      #            cat $logFilePath
+      #            exit 1
+      #          fi
+      #
+      #          if ! grep -q "I am running!" $logFilePath; then
+      #            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but did not contain the expected log output."
+      #            cat $logFilePath
+      #            exit 1
+      #          fi
+      #
+      #          if grep -iq "caused by" $logFilePath; then
+      #            echo "Project generated from archetype ${{ matrix.task.archetype }} started locally, but an unexpected error occurred."
+      #            cat $logFilePath
+      #            exit 1
+      #          fi
+      #
+      #      - name: Verify .gitignore ${{ matrix.task.archetype }}
+      #        working-directory: ./example-${{ matrix.task.archetype }}
+      #        run: |
+      #          if [ ! -f .gitignore ]; then
+      #              ls -lah
+      #              echo "Project generated from archetype does not contain a .gitignore file."
+      #              exit 1
+      #          fi
+      #
+      #      - name: Purge SDK Artifacts from Maven Repository
+      #        run: |
+      #          rm -rf $HOME/.m2/repository/com/sap/cloud/sdk/
+      #      - name: Save Maven Repository
+      #        uses: actions/cache/save@v3
+      #        if: steps.restore-cache.outputs.cache-hit != 'true'
+      #        id: save-cache
+      #        with:
+      #          path: ~/.m2/repository
+      #          key: maven-central
       - name: Fill summary with TODO
         run: |
           echo "# TODO" >> $GITHUB_STEP_SUMMARY
@@ -311,6 +310,59 @@ jobs:
         with:
           category: "/language:java"
 
+  scan:
+    name: "Blackduck Scan"
+    runs-on: ubuntu-latest
+    needs: prepare-release
+    timeout-minutes: 15
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+          ref: ${{ needs.prepare-release.outputs.branch_name }}
+      - name: Setup java
+        uses: actions/setup-java@v3
+        with:
+          distribution: "temurin"
+          java-version: "17"
+          cache: maven
+
+      # Fixme: Use major version from pom once it is 5.x
+      - name: Get SDK Version
+        run: |
+          echo "project_version_NOT_YET_IN_USE=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d '.' -f 1)" >> $GITHUB_ENV
+
+      - name: Determine Maven Excludes
+        run: |
+          python .pipeline/scripts/get-maven-excludes.py --filter-key excludeFromBlackDuckScan --filter-value True
+        id: get-maven-excludes-for-blackduck
+
+      - name: Blackduck Scan
+        uses: SAP/project-piper-action@27cadf261545552a68660531476c0915a97ee3d8
+        with:
+          command: detectExecuteScan
+          flags: \
+            --version=$PROJECT_VERSION \
+        env:
+          PIPER_token: ${{ secrets.BLACKDUCK_TOKEN }}
+          DETECT_MAVEN_EXCLUDED_MODULES: ${{ steps.get-maven-excludes-for-blackduck.outputs.EXCLUDES }},openapi-generator-cli
+          DETECT_MAVEN_BUILD_COMMAND: -pl ${{ steps.get-maven-excludes-for-blackduck.outputs.PREFIXED_EXCLUDES }},!:openapi-generator-cli
+          DETECT_TIMEOUT: 7200
+          # Fixme: Use real project version
+          PROJECT_VERSION: "5"
+
+  create_fosstars_report:
+    name: "Security rating"
+    runs-on: ubuntu-latest
+    needs: prepare-release
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.prepare-release.outputs.branch_name }}
+      - uses: SAP/fosstars-rating-core-action@v1.14.0
+        with:
+          report-branch: fosstars-report
+          token: "${{ secrets.GITHUB_TOKEN }}"
 
   create-release:
     runs-on: ubuntu-latest
@@ -365,7 +417,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   notify-job:
     runs-on: ubuntu-latest
-    needs: [ prepare-release, build, archetypes, codeql, create-release ]
+    needs: [prepare-release, build, archetypes, codeql, create-release]
     if: ${{ failure() }}
     steps:
       - name: Checkout
